config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  
  post 'login', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :article_categories
    has_many :categories, through: :article_categories
    belongs_to :user
    validates :title, presence: true, 
        length: { minimum: 3, maximum: 50 },
        uniqueness: { case_sensitive: false }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "PDR was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "PDR was successfully updated"
      redirect_to article_path(@article) 
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "PDR was successfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
      params.require(:article).permit(:title, :description, :street, :city, :zip, :subdivision, :node, :key, :print, :plant_type, category_ids: [])
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You do not have permission to edit this PDR!"
      redirect_to root_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    @category = Category.find(params[:id])
  end
    
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
    flash[:success] = "Category name was successfully updated"
    redirect_to category_path(@category)
    else
    render 'edit'
    end
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end
    
    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
      redirect_to articles_path if logged_in?
   end
   
   def about
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "You have successfully logged in"
    redirect_to user_path(user)
    else
    flash.now[:danger] = "You've entered incorrect login information!"
    render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5) 
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to XPM ePDR, #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user
      flash[:danger] = "You do not have permission to edit this user!"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
    flash[:danger] = "Only admin users can perform that action"
    redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= article.node %></td>
      <td><%= article.street %></td>
      <td><%= article.zip %></td>
      <td><%= truncate(article.description, length: 30) %></td>
      <td><%= article.user.username if article.user %></td>
      <td><%= article.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
    </tr>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <div class="well">
      <%= form_for @article do |f| %>
      <div class="form-group col-xs-4">
        <%= f.label :title, 'Job Number' %>
        <%= f.text_field :title, class: "form-control", placeholder: "JB123456" %>
      </div>
      
      <div class="form-group col-xs-3">
        <%= f.label :plant, 'Plant (Type):' %>
        <div class="controls">
          <%= f.select(:plant_type, options_for_select([[ 'Underground', 'Underground'], [ 'Aerial', 'Aerial'], [ 'Both', 'Both' ]], :selected => @article.plant_type), {}, {class: "form-control"}) %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-xs-5">
          <div class="input-group cb-box">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
            
          </div>
        </div>
      </div>

      <div class="form-group col-xs-12">
        <%= f.label :street %>
        <%= f.text_field :street, class: "form-control", placeholder: "Street Address" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :city %>
        <%= f.text_field :city, class: "form-control", placeholder: "City" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :zip %>
        <%= f.text_field :zip, class: "form-control", placeholder: "Zip" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :subdivision %>
        <%= f.text_field :subdivision, class: "form-control", placeholder: "Subdivision" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :node %>
        <%= f.text_field :node, class: "form-control", placeholder: "Node Number" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :key %>
        <%= f.text_field :key, class: "form-control", placeholder: "Key Map Page" %>
      </div>
      
      <div class="form-group col-xs-6">
        <%= f.label :print %>
        <%= f.text_field :print, class: "form-control", placeholder: "Print Page" %>
      </div>
      
      <div class="form-group col-xs-12">
        <%= f.label :description, 'Damage Repair Notations:' %>
        <%= f.text_area :description, rows: 6, class: "form-control", placeholder: "Enter Repair Notations... Replace from what to where...etc." %>
      </div>
      
      <div class="form-group">
        <%= f.submit 'Submit PDR', class: 'btn btn-xs btn-success' %>
        <%= link_to "Discard Changes", articles_path, class: 'btn btn-xs btn-warning' %>
      </div>
      <% end %>
      
      
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="form-header" align="center">Edit PDR: <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Plant Damage Reports</h3>
  </div>
  <div align="center">
    <%= will_paginate %>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <tr>
        <th>Job Number</th>
        <th>Node</th>
        <th>Street</th>
        <th>Zip Code</th>
        <th>Damage Repair Notations</th>
        <th>Created By</th>
        <th>Date Created</th>
      </tr>
    <%= render 'article', obj: @articles %>
 
    </table>
  </div>
  <div align="center">
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="form-header" align="center">Create New Plant Damage Report</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="well">
  <div class="page-header">
    <h2 align="center">Plant Damage Report: <span class="label-color"><%= @article.title %></span><small> Created By - <%= link_to @article.user.username, user_path(@article.user) %></small></h3>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading"><span class="glyphicon glyphicon-home"></span>  Location</div>
   
          <table class="table">
            <tr>
              <td><strong>Node:</strong></td>
              <td><%= @article.node %></td>
            </tr>
            <tr>
              <td><strong>Subdivision:</strong></td>
              <td><%= @article.subdivision %></td>
            </tr>
            <tr>
              <td><strong>Key Map:</strong></td>
              <td><%= @article.key %></td>
            </tr>
            <tr>
              <td><strong>Print Page:</strong></td>
              <td><%= @article.print %></td>
            </tr>
            <tr>
              <td><strong>Address:</strong></td>
              <td><%= @article.street %></br><%= @article.city %>, <%= @article.zip %></td>
            </tr>
          </table>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading"><span class="glyphicon glyphicon-warning-sign"></span> Damage Repair Category</div>
          <table class="table table-hover">
            <tr>
              <% if @article.categories.any? %>
                <%= render @article.categories %>
              <% end %>
            </tr>
          </table>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-warning">
        <div class="panel-heading"><i class="fa fa-info"></i>  Plant Details</div>
   
          <table class="table">
            <tr>
              <td><strong>Plant Type:</strong></td>
              <td><%= @article.plant_type %></td>
            </tr>
            <tr class="danger">
              <td><strong>Fiber Count:</strong></td>
              <td><code>"placeholder"</code></td>
            </tr>
            <tr class="danger">
              <td><strong>Coax Size:</strong></td>
              <td><code>"placeholder"</code></td>
            </tr>
            <tr class="danger">
              <td><strong>Depth of Cable:</strong></td>
              <td><code>"placeholder"</code></td>
            </tr>
              <tr class="danger">
              <td><strong>Plant Located:</strong></td>
              <td><code>"placeholder"</code></td>
            </tr>
            <tr class="danger">
              <td><strong>Cable in Conduit:</strong></td>
              <td><code>"placeholder"</code></td>
            </tr>
          </table>
      </div>
    </div>
    
      <div class="col-md-12">
        <div class="panel panel-info">
          <div class="panel-heading"><span class="glyphicon glyphicon-pencil"></span> Damage Repair Notations</div>
     
            <table class="table">
              <tr>
                <td><strong>Notes:</strong></td>
                <td><%= @article.description %></td>
              </tr>
            </table>
        </div>
      </div>

  </div>
  <div class="pdr-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %> 
      <%= link_to edit_article_path(@article), class: "btn btn-xs btn-info" do %>
        <i class="fa fa-pencil-square-o"></i>
        Edit this PDR
        <% end %>
      <%= link_to article_path(@article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you sure?"} do %>
        <i class="fa fa-trash"></i>
        Delete this PDR
        <% end %>
    <% end %>
    <%= link_to articles_path, class: "btn btn-xs btn-success" do %>
      <i class="fa fa-reply"></i>
      Back PDR Listings
      <% end %>
  </div>
</div>
 

app/views/categories/_category.html.erb
<tr class="category-show">
  <td align="center"><%= link_to category.name, category_path(category) %></td>
</tr>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="well">
    <div class="page-header">
      <h1 align="center">Create new category</h1>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-xs btn-success' %>
        <%= link_to "Discard Changes", articles_path, class: 'btn btn-xs btn-warning' %>
      </div>
    </div>
      <% end %>
  </div>

app/views/categories/edit.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="well">
    <div class="page-header">
      <h1 align="center">Edit category</h1>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-xs btn-success' %>
        <%= link_to "Discard Changes", articles_path, class: 'btn btn-xs btn-warning' %>
      </div>
    </div>
      <% end %>
  </div>

app/views/categories/index.html.erb
<div class="well">
  <div class="page-header">
    <h1 align="center">Listing All Categories</h1>
  </div>
  <div align="center">
    <% @categories.each do |category| %>
      <ul class="listing">
        <div class="row">
          <div class="well well-sm col-md-4 col-md-offset-4">
            <li class="list-group">
              <strong><%= link_to "#{category.name}", category_path(category) %></strong> 
            </li>
            <li><small><%= pluralize(category.articles.count, "PDR") %></small></li>
          </div>
        </div>
      </ul>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @category.name + " PDR's" %>
      <% if logged_in? and current_user.admin? %>
      <%= link_to edit_category_path(@category), class: "btn btn-xs btn-info" do %>
        <i class="fa fa-pencil-square-o"></i>
        Edit Category Name
      <% end %>
      <% end %>
    </h3>
  </div>
  <div align="center">
    <%= will_paginate @category_articles %>
  </div>
  <div class="table-responsive">
    <table class="table table-striped">
      <tr>
        <th>Job Number</th>
        <th>Node</th>
        <th>Street</th>
        <th>Zip Code</th>
        <th>Damage Repair Notations</th>
        <th>Created By</th>
        <th>Date Created</th>
      </tr>
    <%= render 'articles/article', obj: @category_articles %>
 
    </table>
  </div>
  <div align="center">
    <%= will_paginate @category_articles %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div>
      <p class="footer-text"><a href="https://youtu.be/ql7uY36-LwA" target="_blank">Puppy Monkey Baby!</a></p>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "XPM ePDR", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "ePDR Index", articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New PDR", new_article_path %></li>
              <!--<li><a href="#">Another action</a></li>-->
              <!--<li><a href="#">Something else here</a></li>-->
              <!--<li role="separator" class="divider"></li>-->
              <!--<li><a href="#">Separated link</a></li>-->
              <!--<li role="separator" class="divider"></li>-->
              <!--<li><a href="#">One more separated link</a></li>-->
            </ul>
          </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Categories", categories_path %></li>
                <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
                <% end %>
                <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create New Category", new_category_path %></li>
              <% end %>
            </ul>
          </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Not working yet...">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li class="Dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Log in', login_path %></li>
        <li><%= link_to 'Sign up', signup_path %></li>
      </ul>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
           

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XPM ePDR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <!--render layots-->
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <!--render layouts footer-->
  <%= render 'layouts/footer' %>
  <!--render debugger-->
  <%= debug(params) if Rails.env.development? %>
  
  <!--Google Analytics-->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-73722076-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>

app/views/pages/about.html.erb
<h1>Stuff to write here</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="xpmhead">
  <h1 class="">XPM ePDR</h1>
  <%= link_to 'Sign up', signup_path, class: "btn btn-primary btn-lg" %>
</div>

<!--<form class="form-signin">-->
<!--<h2 class="form-signin-heading">Please sign in</h2>-->
<!--<label for="inputEmail" class="sr-only">Email address</label>-->
<!--<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>-->
<!--<label for="inputPassword" class="sr-only">Password</label>-->
<!--<input type="password" id="inputPassword" class="form-control" placeholder="Password" required>-->
<!--<div class="checkbox">-->
<!--  <label>-->
<!--    <input type="checkbox" value="remember-me"> Remember me-->
<!--  </label>-->
<!--</div>-->
<!--<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
<!--</form>-->

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-12">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved:
            </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <%= form_for @user do |f| %>
      <div class="form-group">
        <!--<%= f.label :username, 'Username' %>-->
        <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
      </div>
      
      <div class="form-group">
        <!--<%= f.label :email %>-->
        <%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
      </div>
      
      <div class="form-group">
        <!--<%= f.label :password %>-->
        <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
      </div>
      
      <div>
        <%= f.submit(@user.new_record? ? 'Sign Up' : 'Update Account', class: (@user.new_record? ? 'btn btn-sm btn-primary' : 'btn btn-sm btn-success')) %>
        <%= link_to 'Cancel', articles_path, class: 'btn btn-sm btn-default' %>
      </div>
      <% end %>
      
      
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="form-header" align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="well">
  <div class="page-header">
    <h1 align="center">All users</h1>
  </div>
    <div align="center">
      <div align="center">
        <%= will_paginate %>
      </div>
      <% @users.each do |user| %>
        <ul class="listing">
          <div class="row">
            <div class="box-users">
              <div class="">
                <li><%=link_to gravatar_for(user), user_path(user) %></li>
                <li class="article-title">
                  <%= link_to user.username, user_path(user) %>
                </li>
                <li><small><%= pluralize(user.articles.count, "PDR") if user.articles %></small></li>
                <% if logged_in? and current_user.admin? %>
                <li><%= link_to user_path(user), class: "btn btn-xs btn-danger", method: :delete,
                    data: { confirm: "Are you sure you want to delete the user and all their PDRs?" } do %>
                    <i class="fa fa-trash"></i>
                    Delete this user
                    <% end %>
                </li>
              <% end %>
              </div>
            </div>
          </div>
        </ul>
      <% end %>
      <div align="center">
        <%= will_paginate %>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="form-header" align="center">Sign up for XPM ePDR</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="well">
  <h1 align="center"><%= @user.username %>'s PDR's</h1>
    <div class="row">
      <div align="center">
        <%= gravatar_for @user, size: 120 %>
      </div>
    </div>
    </br>
    <div class="table-responsive">
      <table class="table table-striped">
        <tr>
          <th>Job Number</th>
          <th>Node</th>
          <th>Street</th>
          <th>Zip Code</th>
          <th>Damage Repair Notations</th>
          <th>Created By</th>
          <th>Date Created</th>
        </tr>
          <%= render 'articles/article', obj: @user_articles %>
      </table>
    </div>
    <div align="center">
      <%= will_paginate @user_articles %>
    </div>
</div>